### First Stage ###
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV FRONTEND_BASE_URL=${BASE_URL}

RUN npm run build

### Second Stage ###
FROM caddy:2.1.1-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80
EXPOSE 443