version: "3.7"
services:
  
  frontend:
   build:
      context: ./frontend
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: order-fronend
   networks:
    -  mern-stack-net
   depends_on:
    - backend
   stdin_open: true
   tty: true
   
  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
     - 5000:5000
   container_name: order-backend
   networks:
     - mern-stack-net
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local